In [5]:
import pandas as pd
customer_data = pd.read_csv("marketing_campaign.csv", sep="\t")
display(customer_data.head())

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [6]:
customer_shape = customer_data.shape
display(customer_shape)

(2240, 29)

In [7]:
customer_columns = customer_data.columns
display(customer_columns)

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response'],
      dtype='str')

In [8]:
customer_information = customer_data.info()
display(customer_information)

<class 'pandas.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   str
 3   Marital_Status       2240 non-null   str
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   str
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), str(3)
memory usage: 507.6 KB

None

In [9]:
customer_missing_values = customer_data.isnull().sum()
display(customer_missing_values)

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [10]:
dup = customer_data.duplicated().sum()
display(dup)

np.int64(0)

In [11]:
stats = customer_data.describe(include="all")
display(stats)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
count,2240.000000,2240.000000,2240,2240,2216.000000,2240.000000,2240.000000,2240,2240.000000,2240.000000,...,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.0,2240.0,2240.000000
unique,NaN,NaN,5,8,NaN,NaN,NaN,663,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,Graduation,Married,NaN,NaN,NaN,31-08-2012,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,1127,864,NaN,NaN,NaN,12,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,5592.159821,1968.805804,NaN,NaN,52247.251354,0.444196,0.506250,NaN,49.109375,303.935714,...,5.316518,0.072768,0.074554,0.072768,0.064286,0.013393,0.009375,3.0,11.0,0.149107
std,3246.662198,11.984069,NaN,NaN,25173.076661,0.538398,0.544538,NaN,28.962453,336.597393,...,2.426645,0.259813,0.262728,0.259813,0.245316,0.114976,0.096391,0.0,0.0,0.356274
min,0.000000,1893.000000,NaN,NaN,1730.000000,0.000000,0.000000,NaN,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
25%,2828.250000,1959.000000,NaN,NaN,35303.000000,0.000000,0.000000,NaN,24.000000,23.750000,...,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
50%,5458.500000,1970.000000,NaN,NaN,51381.500000,0.000000,0.000000,NaN,49.000000,173.500000,...,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
75%,8427.750000,1977.000000,NaN,NaN,68522.000000,1.000000,1.000000,NaN,74.000000,504.250000,...,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
max,11191.000000,1996.000000,NaN,NaN,666666.000000,2.000000,2.000000,NaN,99.000000,1493.000000,...,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.0,11.0,1.000000

In [12]:
data = customer_data.head(10)
display(data)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0
5,7446,1967,Master,Together,62513.0,0,1,09-09-2013,16,520,...,6,0,0,0,0,0,0,3,11,0
6,965,1971,Graduation,Divorced,55635.0,0,1,13-11-2012,34,235,...,6,0,0,0,0,0,0,3,11,0
7,6177,1985,PhD,Married,33454.0,1,0,08-05-2013,32,76,...,8,0,0,0,0,0,0,3,11,0
8,4855,1974,PhD,Together,30351.0,1,0,06-06-2013,19,14,...,9,0,0,0,0,0,0,3,11,1
9,5899,1950,PhD,Together,5648.0,1,1,13-03-2014,68,28,...,20,1,0,0,0,0,0,3,11,0

In [13]:
cust = customer_data.copy()
cust["Age"] = 2026 - cust["Year_Birth"]
age = cust[["Year_Birth", "Age"]]
display(age.head(10))

   Year_Birth  Age
0        1957   69
1        1954   72
2        1965   61
3        1984   42
4        1981   45
5        1967   59
6        1971   55
7        1985   41
8        1974   52
9        1950   76

In [14]:
cust["Total_Purchases"] = (
    cust["NumWebPurchases"] +
    cust["NumCatalogPurchases"] +
    cust["NumStorePurchases"])
purchase = cust[["ID", "Total_Purchases"]]
display(purchase.head(10))

     ID  Total_Purchases
0  5524               22
1  2174                4
2  4141               20
3  6182                6
4  5324               14
5  7446               20
6   965               17
7  6177                8
8  4855                5
9  5899                1

In [15]:
cust["Total_Spent"] = (cust["MntWines"] + cust["MntFruits"] + cust["MntMeatProducts"] + cust["MntFishProducts"] + cust["MntSweetProducts"] + cust["MntGoldProds"])

In [16]:
display(cust.columns)

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response',
       'Age', 'Total_Purchases', 'Total_Spent'],
      dtype='str')

In [17]:
cust["Customer_Value"] = cust["Total_Spent"] * cust["Total_Purchases"]
value = cust[["ID", "Total_Spent", "Total_Purchases", "Customer_Value"]]
display(value.head(10))

     ID  Total_Spent  Total_Purchases  Customer_Value
0  5524         1617               22           35574
1  2174           27                4             108
2  4141          776               20           15520
3  6182           53                6             318
4  5324          422               14            5908
5  7446          716               20           14320
6   965          590               17           10030
7  6177          169                8            1352
8  4855           46                5             230
9  5899           49                1              49

In [18]:
cust["Segment"] = "Low"

cust.loc[cust["Customer_Value"] >= 5000, "Segment"] = "Medium"
cust.loc[cust["Customer_Value"] >= 15000, "Segment"] = "High"

In [19]:
segment = cust[["ID", "Customer_Value", "Segment"]]
display(segment.head(10))

     ID  Customer_Value Segment
0  5524           35574    High
1  2174             108     Low
2  4141           15520    High
3  6182             318     Low
4  5324            5908  Medium
5  7446           14320  Medium
6   965           10030  Medium
7  6177            1352     Low
8  4855             230     Low
9  5899              49     Low

In [20]:
seg_count = cust["Segment"].value_counts()
display(seg_count)

Segment
Low       1115
High       741
Medium     384
Name: count, dtype: int64

In [21]:
high = cust[cust["Segment"] == "High"]
display(high.head(10))

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Age,Total_Purchases,Total_Spent,Customer_Value,Segment
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,0,0,3,11,1,69,22,1617,35574,High
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,0,0,3,11,0,61,20,776,15520,High
12,2125,1959,Graduation,Divorced,63033.0,0,0,15-11-2013,82,194,...,0,0,3,11,0,67,15,1102,16530,High
15,2114,1946,PhD,Single,82800.0,0,0,24-11-2012,23,1006,...,0,0,3,11,1,80,25,1315,32875,High
18,6565,1949,Master,Married,76995.0,0,1,28-03-2013,91,1012,...,0,0,3,11,0,77,24,1782,42768,High
21,5376,1979,Graduation,Married,2447.0,1,0,06-01-2013,42,1,...,0,0,3,11,0,47,28,1730,48440,High
27,5255,1986,Graduation,Single,NaN,1,0,20-02-2013,19,5,...,0,0,3,11,0,40,27,637,17199,High
29,1966,1965,PhD,Married,84618.0,0,0,22-11-2013,96,684,...,0,0,3,11,0,61,25,1672,41800,High
34,8755,1946,Master,Married,68657.0,0,0,20-02-2013,4,482,...,0,0,3,11,0,80,17,1196,20332,High
36,4339,1970,PhD,Married,67353.0,0,1,31-12-2013,37,702,...,0,0,3,11,0,56,23,913,20999,High

In [22]:
medium = cust[cust["Segment"] == "Medium"]
display(medium.head(10))

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Age,Total_Purchases,Total_Spent,Customer_Value,Segment
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,0,0,3,11,0,45,14,422,5908,Medium
5,7446,1967,Master,Together,62513.0,0,1,09-09-2013,16,520,...,0,0,3,11,0,59,20,716,14320,Medium
6,965,1971,Graduation,Divorced,55635.0,0,1,13-11-2012,34,235,...,0,0,3,11,0,55,17,590,10030,Medium
22,1993,1949,PhD,Married,58607.0,0,1,23-12-2012,63,867,...,0,0,3,11,0,77,14,972,13608,Medium
23,4047,1954,PhD,Married,65324.0,0,1,11-01-2014,0,384,...,0,0,3,11,0,72,17,544,9248,Medium
24,1409,1951,Graduation,Together,40689.0,0,1,18-03-2013,69,270,...,0,0,3,11,0,75,13,444,5772,Medium
45,1371,1976,Graduation,Single,79941.0,0,0,28-06-2014,72,123,...,0,0,3,11,0,50,15,984,14760,Medium
50,8614,1957,Graduation,Widow,65486.0,0,1,12-05-2014,29,245,...,0,0,3,11,0,69,16,507,8112,Medium
54,9381,1978,Graduation,Married,66373.0,1,1,12-06-2013,57,328,...,0,0,3,11,0,48,16,606,9696,Medium
59,8375,1968,PhD,Married,55954.0,0,1,03-03-2014,63,447,...,0,0,3,11,0,58,16,518,8288,Medium

In [23]:
low = cust[cust["Segment"] == "Low"]
display(low.head(10))

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Age,Total_Purchases,Total_Spent,Customer_Value,Segment
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,0,0,3,11,0,72,4,27,108,Low
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,0,0,3,11,0,42,6,53,318,Low
7,6177,1985,PhD,Married,33454.0,1,0,08-05-2013,32,76,...,0,0,3,11,0,41,8,169,1352,Low
8,4855,1974,PhD,Together,30351.0,1,0,06-06-2013,19,14,...,0,0,3,11,1,52,5,46,230,Low
9,5899,1950,PhD,Together,5648.0,1,1,13-03-2014,68,28,...,0,0,3,11,0,76,1,49,49,Low
10,1994,1983,Graduation,Married,NaN,1,0,15-11-2013,11,5,...,0,0,3,11,0,43,3,19,57,Low
11,387,1976,Basic,Married,7500.0,0,0,13-11-2012,59,6,...,0,0,3,11,0,50,5,61,305,Low
13,8180,1952,Master,Divorced,59354.0,1,1,15-11-2013,53,233,...,0,0,3,11,0,74,12,310,3720,Low
14,2569,1987,Graduation,Married,17323.0,0,0,10-10-2012,38,3,...,0,0,3,11,0,39,4,46,184,Low
16,9736,1980,Graduation,Married,41850.0,1,1,24-12-2012,51,53,...,0,0,3,11,0,46,6,96,576,Low

In [24]:
email = cust[["ID", "Income", "Age", "Total_Spent", "Total_Purchases", "Customer_Value", "Segment"]]
display(email.head(10))

     ID   Income  Age  Total_Spent  Total_Purchases  Customer_Value Segment
0  5524  58138.0   69         1617               22           35574    High
1  2174  46344.0   72           27                4             108     Low
2  4141  71613.0   61          776               20           15520    High
3  6182  26646.0   42           53                6             318     Low
4  5324  58293.0   45          422               14            5908  Medium
5  7446  62513.0   59          716               20           14320  Medium
6   965  55635.0   55          590               17           10030  Medium
7  6177  33454.0   41          169                8            1352     Low
8  4855  30351.0   52           46                5             230     Low
9  5899   5648.0   76           49                1              49     Low

In [25]:
import matplotlib.pyplot as plt
seg = cust["Segment"].value_counts()
plt.figure(figsize=(6,4))
plt.bar(seg.index, seg.values)
plt.title("Customer Segment Distribution")
plt.xlabel("Segment")
plt.ylabel("Customers")
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
age = cust["Age"]
plt.figure(figsize=(6,4))
plt.hist(age, bins=10)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Customers")
plt.show()

In [ ]:
inc = cust["Income"].dropna()
plt.figure(figsize=(6,4))
plt.hist(inc, bins=10)
plt.title("Income Distribution")
plt.xlabel("Income")
plt.ylabel("Customers")
plt.show()

In [ ]:
sp = cust.groupby("Segment")["Total_Spent"].mean()
plt.figure(figsize=(6,4))
plt.bar(sp.index, sp.values)
plt.title("Average Spending by Segment")
plt.xlabel("Segment")
plt.ylabel("Average Spending")
plt.show()

In [ ]:
res = cust["Response"].value_counts()
plt.figure(figsize=(6,4))
plt.bar(res.index.astype(str), res.values)
plt.title("Campaign Response")
plt.xlabel("Response")
plt.ylabel("Customers")
plt.show()